INSERT INTO pergunta(id,pergunta) VALUES (1,'É comestível?');
INSERT INTO pergunta(id,pergunta) VALUES (2,'Cítrica?');
INSERT INTO pergunta(id,pergunta) VALUES (3,'Formato circular?');
INSERT INTO pergunta(id,pergunta) VALUES (4,'Tem coroa?');
INSERT INTO pergunta(id,pergunta) VALUES (5,'Casca verde?');
INSERT INTO pergunta(id,pergunta) VALUES (6,'Casca laranja?');
INSERT INTO pergunta(id,pergunta) VALUES (7,'Fácil de descascar?');
INSERT INTO pergunta(id,pergunta) VALUES (8,'Casca vermelha?');
INSERT INTO pergunta(id,pergunta) VALUES (9,'Semi-ácida?');
INSERT INTO pergunta(id,pergunta) VALUES (10,'É nativa do Brasil');
INSERT INTO pergunta(id,pergunta) VALUES (11,'Cabem mais de 5 na mão?');
INSERT INTO pergunta(id,pergunta) VALUES (12,'Possui as sementes do lado de fora?');
INSERT INTO pergunta(id,pergunta) VALUES (13,'Fruta enfeitiçada no conto da Branca de Neve?');
INSERT INTO pergunta(id,pergunta) VALUES (14,'Tem uma única semente?');
INSERT INTO pergunta(id,pergunta) VALUES (15,'Possui casca aveludada?');
INSERT INTO pergunta(id,pergunta) VALUES (16,'Casca amarela?');
INSERT INTO pergunta(id,pergunta) VALUES (17,'Possui casca lisa?');
INSERT INTO pergunta(id,pergunta) VALUES (18,'Instrumento Musical?');
INSERT INTO pergunta(id,pergunta) VALUES (19,'Instrumento de Sopro?');
INSERT INTO pergunta(id,pergunta) VALUES (20,'Instrumento de cordas?');
INSERT INTO pergunta(id,pergunta) VALUES (21,'Usa palheta?');
INSERT INTO pergunta(id,pergunta) VALUES (22,'É um eletrônico?');
INSERT INTO pergunta(id,pergunta) VALUES (23,'Tira foto?');
INSERT INTO pergunta(id,pergunta) VALUES (24,'Faz Ligações?');
INSERT INTO pergunta(id,pergunta) VALUES (25,'Específico para ouvir música?');
INSERT INTO pergunta(id,pergunta) VALUES (26,'Voltado para jogos?');
INSERT INTO pergunta(id,pergunta) VALUES (27,'É de mobília?');
INSERT INTO pergunta(id,pergunta) VALUES (28,'Sentamos nele?');
INSERT INTO pergunta(id,pergunta) VALUES (29,'cabe mais de uma pessoa?');
INSERT INTO pergunta(id,pergunta) VALUES (30,'Guarda outros objetos?');
INSERT INTO pergunta(id,pergunta) VALUES (31,'Vestimenta?');
INSERT INTO pergunta(id,pergunta) VALUES (32,'Calçado?');
INSERT INTO pergunta(id,pergunta) VALUES (33,'Social?');
INSERT INTO pergunta(id,pergunta) VALUES (34,'Traje de banho?');
INSERT INTO pergunta(id,pergunta) VALUES (35,'Masculino?');
INSERT INTO pergunta(id,pergunta) VALUES (36,'Objeto de cozinha?');
INSERT INTO pergunta(id,pergunta) VALUES (37,'Talher?');
INSERT INTO pergunta(id,pergunta) VALUES (38,'Corta a comida?');
INSERT INTO pergunta(id,pergunta) VALUES (39,'voltado para o consumo de líquidos?');
INSERT INTO pergunta(id,pergunta) VALUES (40,'Usado para medir?');
INSERT INTO pergunta(id,pergunta) VALUES (41,'Usado para escrever?');
