CREATE TABLE item(
   id    INTEGER  NOT NULL PRIMARY KEY
  ,label VARCHAR(14) NOT NULL
);
INSERT INTO item(id,label) VALUES (1,'Armário');
INSERT INTO item(id,label) VALUES (2,'Borracha');
INSERT INTO item(id,label) VALUES (3,'Cadeira');
INSERT INTO item(id,label) VALUES (4,'Câmera');
INSERT INTO item(id,label) VALUES (5,'Caneta');
INSERT INTO item(id,label) VALUES (6,'Celular');
INSERT INTO item(id,label) VALUES (7,'Chapéu');
INSERT INTO item(id,label) VALUES (8,'Chuteira');
INSERT INTO item(id,label) VALUES (9,'Colher');
INSERT INTO item(id,label) VALUES (10,'Copo');
INSERT INTO item(id,label) VALUES (11,'Faca');
INSERT INTO item(id,label) VALUES (12,'Maiô');
INSERT INTO item(id,label) VALUES (13,'Mesa');
INSERT INTO item(id,label) VALUES (14,'Videogame');
INSERT INTO item(id,label) VALUES (15,'Panela');
INSERT INTO item(id,label) VALUES (16,'Rádio');
INSERT INTO item(id,label) VALUES (17,'Régua');
INSERT INTO item(id,label) VALUES (18,'Sapato');
INSERT INTO item(id,label) VALUES (19,'Saxofone');
INSERT INTO item(id,label) VALUES (20,'Sofá');
INSERT INTO item(id,label) VALUES (21,'Sunga');
INSERT INTO item(id,label) VALUES (22,'Teclado');
INSERT INTO item(id,label) VALUES (23,'Trompete');
INSERT INTO item(id,label) VALUES (24,'TV');
INSERT INTO item(id,label) VALUES (25,'Violão');
INSERT INTO item(id,label) VALUES (26,'Abacate');
INSERT INTO item(id,label) VALUES (27,'Abacaxi');
INSERT INTO item(id,label) VALUES (28,'Acerola');
INSERT INTO item(id,label) VALUES (29,'Banana');
INSERT INTO item(id,label) VALUES (30,'Cajú');
INSERT INTO item(id,label) VALUES (31,'Caqui');
INSERT INTO item(id,label) VALUES (32,'Cereja');
INSERT INTO item(id,label) VALUES (33,'Coco');
INSERT INTO item(id,label) VALUES (34,'Fruta do Conde');
INSERT INTO item(id,label) VALUES (35,'Goiaba');
INSERT INTO item(id,label) VALUES (36,'Jabuticaba');
INSERT INTO item(id,label) VALUES (37,'Jaca');
INSERT INTO item(id,label) VALUES (38,'Kiwi');
INSERT INTO item(id,label) VALUES (39,'Laranja');
INSERT INTO item(id,label) VALUES (40,'Limão');
INSERT INTO item(id,label) VALUES (41,'Maçã');
INSERT INTO item(id,label) VALUES (42,'Mamão');
INSERT INTO item(id,label) VALUES (43,'Maracujá');
INSERT INTO item(id,label) VALUES (44,'Melancia');
INSERT INTO item(id,label) VALUES (45,'Melão');
INSERT INTO item(id,label) VALUES (46,'Morango');
INSERT INTO item(id,label) VALUES (47,'Pera');
INSERT INTO item(id,label) VALUES (48,'Pêssego');
INSERT INTO item(id,label) VALUES (49,'Tangerina');
INSERT INTO item(id,label) VALUES (50,'Uva');
